// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        // 🛡️ BLINDAJE: En lugar de un error críptico, lanzamos una advertencia clara
        // para que la app no se cierre sin que sepas por qué.
        throw UnsupportedError(
          'Firebase no está configurado para Linux en este proyecto. Reconfigura con FlutterFire CLI.',
        );
      default:
        // 🛡️ BLINDAJE: Caso de emergencia para plataformas desconocidas
        throw UnsupportedError(
          'La plataforma actual no es compatible con la configuración actual de Firebase.',
        );
    }
  }

  // 🛡️ TUS CREDENCIALES (NO SE TOCAN, SE MANTIENEN IGUAL):
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvpFr25U4xCZv-8L8htyf6EQ7z3KLg6Og',
    appId: '1:279510411630:web:00ff48135d12ec1427397f',
    messagingSenderId: '279510411630',
    projectId: 'barrio-seguro-b0692',
    authDomain: 'barrio-seguro-b0692.firebaseapp.com',
    storageBucket: 'barrio-seguro-b0692.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmEqVgVSHHV5u_d0u0tmXZSQDYY-76rZY',
    appId: '1:279510411630:android:7697ed19c452ec1f27397f',
    messagingSenderId: '279510411630',
    projectId: 'barrio-seguro-b0692',
    storageBucket: 'barrio-seguro-b0692.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAuiod2o7erqtY4jF9vSwhKYmC-ZPVEd-Q',
    appId: '1:279510411630:ios:da5335eee77d2a2c27397f',
    messagingSenderId: '279510411630',
    projectId: 'barrio-seguro-b0692',
    storageBucket: 'barrio-seguro-b0692.firebasestorage.app',
    iosBundleId: 'com.example.miApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAuiod2o7erqtY4jF9vSwhKYmC-ZPVEd-Q',
    appId: '1:279510411630:ios:da5335eee77d2a2c27397f',
    messagingSenderId: '279510411630',
    projectId: 'barrio-seguro-b0692',
    storageBucket: 'barrio-seguro-b0692.firebasestorage.app',
    iosBundleId: 'com.example.miApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCvpFr25U4xCZv-8L8htyf6EQ7z3KLg6Og',
    appId: '1:279510411630:web:d92960bffd26bee427397f',
    messagingSenderId: '279510411630',
    projectId: 'barrio-seguro-b0692',
    authDomain: 'barrio-seguro-b0692.firebaseapp.com',
    storageBucket: 'barrio-seguro-b0692.firebasestorage.app',
  );
}
